### ISSUE TITLE
Segfault is caused in incredibly specific circumstances

### ISSUE THREAD

**Issue by NeRdTheNed** [Scotsguy/now-playing#4] opened 2020-08-07 15:27 UTC
See [#Nuclearfarts/connected-block-textures#12 ](https://github.com/Nuclearfarts/connected-block-textures/issues/12#issuecomment-670565144) for known details of the issue. This is likely an indication of incompatibility with something that Canvas or Connected Block Textures is doing.

**Comment by TwilightFlower** [comment] 2020-08-07 21:31
More likely, it's caused by an incompatibility with the specific code path that Canvas takes when CBT is installed due to a (recently fixed) bug in CBT. See https://github.com/grondag/canvas/issues/71 for that.

**Comment by Scotsguy** [comment] 2020-08-26 13:52
Fixed in Canvas, it seems

**Closed as completed by Scotsguy** 2020-08-26 13:52 UTC
Labels: E/external
